[package]
name = "fastfibo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 1
panic = "abort"

[dependencies]
libc = "0.2.103"
tailcall = "0.1.6"